module.exports = [
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_.jpg",
    title: "Rogue One",
    slug: "Rogue-One",
    desc: "In a time of conflict, a group of unlikely heroes band together on a mission to steal the plans to the Death Star, the Empire's ultimate weapon of destruction.",
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Gareth Edwards",
    duration: "2 hour 13 minutes",
    cast: ["Felicity Jones", "Diego Luna", "Alan Tudyk"],
    isShowing: true,
    basicPrice: 80000,
  },
  {
    poster: "https://cdn.cgv.id/uploads/movie/pictures/21013400.jpg",
    title: "DUNE",
    slug: "DUNE",
    desc: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
    genres: ["Action", "Adventure", "Drama"],
    director: "Denis Villeneuve",
    duration: "2 hours 35 minutes ",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya"],
    isShowing: true,
    basicPrice: 80000,
  },
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTk0NDYwMTkyN15BMl5BanBnXkFtZTgwMTg2NzE4NTE@._V1_FMjpg_UX1000_.jpg",
    title: "Kimatica",
    slug: "Kimatica",
    desc: "We may be quick to blame secret organizations, corporations and corrupt politicians for the state of the environment. The harsh truth is that the world is in its current state because humanity is evolving and taking the world with it.",
    genres: ["Decomentary"],
    director: "Benjamin Stewart",
    duration: "1 hour 24 minutes",
    cast: ["Bruce Lipton", "Henrik Palmgren", "Benjamin Stewart"],
    isShowing: false,
    basicPrice: 80000,
  },
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTQ1OTU0ODcxMV5BMl5BanBnXkFtZTcwOTMxNTUwOA@@._V1_.jpg",
    title: "Ted",
    slug: "Ted",
    desc: "John Bennett, a man whose childhood wish of bringing his teddy bear to life came true, now must decide between keeping the relationship with the bear, Ted or his girlfriend, Lori.",
    genres: ["Comedys"],
    director: "Seth MacFarlane",
    duration: " 1 hour 46 minutes ",
    cast: ["Mark Wahlberg", "Mila Kunis", "Seth MacFarlane"],
    isShowing: true,
    basicPrice: 80000,
  },
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjEwMDg3MDk1NF5BMl5BanBnXkFtZTgwNjYyODA1NTE@._V1_.jpg",
    title: "Ted 2",
    slug: "Ted-2",
    desc: "Newlywed couple Ted and Tami-Lynn want to have a baby, but in order to qualify to be a parent, Ted will have to prove he's a person in a court of law.",
    genres: ["Comedys"],
    director: "Seth MacFarlane",
    duration: " 1 hour 55 minutes ",
    cast: ["Mark Wahlberg", "Seth MacFarlane", "Amanda Seyfried"],
    isShowing: true,
    basicPrice: 80000,
  },
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BYmRiYjQ0OGQtYTAzMi00OGVjLWE4YTQtM2Q4YjBlZTBhMWM5XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
    title: "Who Am I",
    slug: "Who-Am-I",
    desc: "Benjamin, a young German computer whiz, is invited to join a subversive hacker group that wants to be noticed on the world's stage.",
    genres: ["Crime", "Drama", "Mystery"],
    director: " Baran bo Odar ",
    duration: " 1 hour 42 minutes ",
    cast: ["Tom Schilling", "Elyas M'Barek", "Wotan Wilke Möhring"],
    isShowing: true,
    month_show: "oct",
    basicPrice: 80000,
  },
  {
    poster:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Influencer_Poster.png/800px-Influencer_Poster.png",
    title: "Influencer",
    slug: "Influencer",
    desc: "Social media fame is the ultimate curse in writer-director Kurtis David Harder’s latest. Released as a Shudder Original, Influencer set itself apart from traditional horror fare by flipping a well-worn trope on its head. From Single White Female to Ingrid Goes West, there’s no shortage of movies about lonely girls making trouble, but this film’s clever twists and shocking turns (particularly after the title sequence) left IMDb fans calling it the most underrated horror movie of the year.",
    release: "June 28, 2017",
    director: "Jon Watss",
    duration: "2 hours 13 minutes ",
    cast: ["tom holland", "michael keaton", "robert downey jr"],
    genres: ["horror", "mystery", "thriller"],
    isShowing: false,
    month_show: "oct",
    basicPrice: 80000,
  },
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BZDQxZTY0ZDItY2Y0Yy00OTIzLTkwYTgtNmNkODhiYTk4MzUwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    title: "Infinity Pool",
    slug: "Infinity-Pool",
    desc: "James and Em Foster are enjoying an all-inclusive beach vacation in the fictional island of La Tolqa, when a fatal accident exposes the resort's perverse subculture of hedonistic tourism, reckless violence and surreal horrors.",
    release: "June 28, 2017",
    director: "Jon Watss",
    duration: "2 hours 13 minutes ",
    cast: ["tom holland", "michael keaton", "robert downey jr"],
    genres: ["crime", "horror", "mystery"],
    isShowing: false,
    month_show: "oct",
    basicPrice: 80000,
  },
  {
    poster:
      "https://www.themoviedb.org/t/p/original/jFC4LS5qTAT3PinzdEzINfu1CV9.jpg",
    title: "The Pope's Exorcist",
    slug: "The-Pope's-Exorcist",
    desc: "Follow Gabriele Amorth, the Vatican's leading exorcist, as he investigates the possession of a child and uncovers a conspiracy the Vatican has tried to keep secret.",
    release: "June 28, 2017",
    director: "Jon Watss",
    duration: "2 hours 13 minutes ",
    cast: ["tom holland", "michael keaton", "robert downey jr"],
    genres: ["horror", "thriller"],
    isShowing: false,
    month_show: "oct",
    basicPrice: 80000,
  },
  {
    poster:
      "https://m.media-amazon.com/images/M/MV5BMmY5ZGE4NmUtZWI4OS00ZWJmLWFjMzgtOWUyZjI4NDg3Y2E5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    title: "Talk to Me",
    slug: "Talk-to-Me",
    desc: "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
    release: "June 28, 2017",
    director: "Jon Watss",
    duration: "2 hours 13 minutes ",
    cast: ["tom holland", "michael keaton", "robert downey jr"],
    genres: ["horror", "thriller"],
    isShowing: false,
    month_show: "oct",
    basicPrice: 80000,
  },
];
